import test from 'node:test';
import assert from 'node:assert/strict';
import {applyProposal,parseActiveWork,validateRoute} from '../src/control/contracts.js';
import {createGitHubAdapter} from '../src/control/adapters.js';
import {createControlService,createMemoryStore} from '../src/control/service.js';

const active='# Active Work\n\n## Current active workstreams\n\n### UGC Creator App / media asset lifecycle\n**Current stage:** architecture locked  \n**Current objective:** Photos → iCloud remains active.  \n**Next bounded action:** Implement the archive slice.  \n\n### AI second brain / shared AI operating system\n**Current stage:** implementation  \n**Current objective:** Build /control/.  \n**Next decision:** Verify locally.  \n\n## Session handoff rule\n';
const route={route_kind:'state_update',responsibility:'needs_ashley',confidence:'high',plain_summary:'Update the control-plane stage',why:'Ashley changed priority',project_id:'ai-second-brain-shared-ai-operating-system',proposal:{target_repo:'ashleybrookeugc/research-vault',target_path:'ACTIVE_WORK.md',operation:'replace_field',section:'AI second brain / shared AI operating system',field:'Current stage',value:'local proof complete'}};

test('dashboard parser keeps active workstreams including Photos to iCloud',()=>{const rows=parseActiveWork(active);assert.equal(rows.length,2);assert.match(rows[0]['Current objective'],/Photos → iCloud/);});
test('route contract fails closed on writes outside research-vault',()=>{assert.throws(()=>validateRoute({...route,proposal:{...route.proposal,target_repo:'ashleybrookeugc/B-Paid'}}),/not allowed/);});
test('approved proposal replaces only its named field',()=>{const out=applyProposal(active,route.proposal);assert.match(out,/Current stage:\*\* local proof complete/);assert.match(out,/Photos → iCloud remains active/);});
test('GitHub adapter uses read/write scopes and blocks product-repo writes',async()=>{const calls=[];const fetchImpl=async(url,options={})=>{calls.push({url,options});if(options.method==='PUT')return new Response(JSON.stringify({commit:{sha:'commit1'},content:{sha:'blob2'}}),{status:200});return new Response(JSON.stringify({sha:'blob1',content:btoa('hello')}),{status:200});};const github=createGitHubAdapter({fetchImpl,tokenProvider:async scope=>'token-'+scope});assert.equal((await github.readFile('ashleybrookeugc/ugc-creator-app','docs/PROJECT_INDEX.md')).content,'hello');await github.writeFile('ashleybrookeugc/research-vault','ACTIVE_WORK.md','next','blob1','message');await assert.rejects(()=>github.writeFile('ashleybrookeugc/ugc-creator-app','x','x','s','m'),/restricted/);assert.equal(calls[0].options.headers.authorization,'Bearer token-read');assert.equal(calls[1].options.headers.authorization,'Bearer token-write');});
test('capture, approve and reject run end to end with doubles',async()=>{let markdown=active;const writes=[];const github={async readFile(){return{content:markdown,sha:'before'}},async writeFile(repo,path,content){markdown=content;writes.push({repo,path});return{commit_sha:'verified-commit'}}};const store=createMemoryStore();const router={async route(){return route}};const service=createControlService({github,store,router});const captured=await service.capture('The control slice is ready for local proof.');assert.equal(captured.queue_item.id,'q1');assert.equal((await service.state()).queues.needs_ashley.length,1);const approved=await service.approve('q1');assert.equal(approved.receipt.commit_sha,'verified-commit');assert.equal(writes[0].repo,'ashleybrookeugc/research-vault');assert.match(markdown,/local proof complete/);await service.capture('Again');await service.reject('q2','Not now');assert.equal((await service.state()).queues.needs_ashley.length,0);});
